countries_dict = {
  'CA': ['Canada', 18, 19],
  'AU': ['Australia', 21, 39],
  'AE': ['United Arab Emirates', 1, 1],
  'IT': ['Italy', 15, 18],
  'AR': ['Argentina', 1, 1],
  'BE': ['Belgium', 608, 775],
  'VA': ['Vatican City', 2, 3],
  'NL': ['Netherlands', 1382, 1724],
  'SG': ['Singapore', 4, 5],
  'MY': ['Malaysia', 5, 9],
  'CL': ['Chile', 2, 2],
  'JP': ['Japan', 17, 28],
  'DE': ['Germany', 2, 3],
  'ZA': ['South Africa', 4, 7],
  'PT': ['Portugal', 14, 15],
  'LU': ['Luxembourg', 18, 20],
  'MT': ['Malta', 2, 2],
  'DK': ['Denmark', 9, 11],
  'US': ['United States of America', 30, 67],
  'FR': ['France', 460, 730],
  'RU': ['Russia', 6, 6],
  'CN': ['South China Sea Islands (disputed)', 8, 10],
  'ES': ['Spain', 6, 8],
  'CH': ['Switzerland', 2, 3],
  'TH': ['Thailand', 4, 4],
  'IE': ['Ireland', 3, 3],
  'PL': ['Poland', 1, 1],
  'GB': ['United Kingdom', 6, 8],
  'IN': ['India', 33, 72],
  'AT': ['Austria', 8, 10]
}
