#!/usr/bin/python3

from geopy.geocoders import Nominatim
from geopy.geocoders import GeoNames
from geopy.geocoders import MapBox

import api_credentials

try:
    geolocator1 = Nominatim(user_agent=api_credentials.nominatim_agent)
    geolocator2 = GeoNames(username=api_credentials.geonames_user)
    geolocator3 = MapBox(api_key=api_credentials.mapbox_token)
except:
    print("ERROR: FATAL: Unable to get geolocator")
    sys.exit()


def getCountryInfo(lat, long):

    latitude = int(lat)
    longitude = int(long)
    lat_codes = latitude_dict[latitude]
    long_codes = longitude_dict[longitude]
    codes = lat_codes.intersection(long_codes)

    if len(codes) == 1:
        code = codes.pop()
        name = countries_dict[code]
    else:
        latlong = (lat, long)
        # get info from Nominatim
        try:
            location = geolocator1.reverse(latlong, language='en-US', exactly_one=True)
            code = location.raw['address']['country_code'].upper()
            name = location.raw['address']['country']
        except:
            code = ''
            name = ''
        # get info from GeoNames if not found in Nominatim
        if code == '':
            try:
                location = geolocator2.reverse(latlong, lang='en-US', exactly_one=True)
                code = location.raw['countryCode']
                name = location.raw['countryName']
            except:
                pass
        # get info from MapBox if not found in Nominatim and Geocodes
        if code == '':
            try:
                location = geolocator3.reverse(latlong, exactly_one=True)
                location_info = location.raw['context']
                len_info = len(location_info)
                if len_info > 4:
                    info_index = 3
                else:
                    info_index = len_info - 1
                code = location_info[info_index]['short_code'].upper()
                name = location_info[info_index]['text']
                if len(code) > 2:
                    code = code[:2]
                    name = ''
            except:
                pass

    return [code, name]


countries_dict = {
  'IN': 'India',
  'TM': 'Turkmenistan',
  'FJ': 'Fiji',
  'MW': 'Malawi',
  'MA': 'Morocco',
  'VA': 'Vatican City',
  'SS': 'South Sudan',
  'BF': 'Burkina Faso',
  'GY': 'Guyana',
  'OM': 'Oman',
  'EH': 'Western Sahara',
  'BN': 'Brunei Darussalam',
  'GB': 'United Kingdom',
  'CI': 'Côte d\'Ivoire',
  'LB': 'Lebanon',
  'JM': 'Jamaica',
  'GA': 'Gabon',
  'PA': 'Panama',
  'DK': 'Denmark',
  'IQ': 'Iraq',
  'BJ': 'Benin',
  'MZ': 'Mozambique',
  'LU': 'Luxembourg',
  'FK': 'Falkland Islands',
  'GQ': 'Equatorial Guinea',
  'CG': 'Congo',
  'RU': 'Russia',
  'ER': 'Eritrea',
  'CD': 'Democratic Republic of the Congo',
  'LV': 'Latvia',
  'AO': 'Angola',
  'RW': 'Rwanda',
  'MT': 'Malta',
  'SY': 'Syria',
  'AU': 'Australia',
  'AM': 'Armenia',
  'EC': 'Ecuador',
  'TD': 'Chad',
  'AR': 'Argentina',
  'AZ': 'Azerbaijan',
  'MR': 'Mauritania',
  'MN': 'Mongolia',
  'FR': 'France',
  'TZ': 'Tanzania',
  'BI': 'Burundi',
  'CH': 'Switzerland',
  'ZA': 'South Africa',
  'BO': 'Bolivia',
  'SO': 'Somalia',
  'CF': 'Central African Republic',
  'TR': 'Turkey',
  'GW': 'Guinea-Bissau',
  'PK': 'Pakistan',
  'WS': 'Samoa',
  'CA': 'Canada',
  'EE': 'Estonia',
  'ZW': 'Zimbabwe',
  'KP': 'North Korea',
  'PT': 'Portugal',
  'TJ': 'Tajikistan',
  'LA': 'Laos',
  'BD': 'Bangladesh',
  'GE': 'Georgia',
  'IE': 'Ireland',
  'KI': 'Kiribati',
  'GH': 'Ghana',
  'JE': 'Jersey',
  'KW': 'Kuwait',
  'SB': 'Solomon Islands',
  'FM': 'Micronesia',
  'PS': 'Palestinian Territory',
  'GN': 'Guinea',
  'PE': 'Peru',
  'NO': 'Norway',
  'JO': 'Jordan',
  'MG': 'Madagascar',
  'VE': 'Venezuela',
  'AG': 'Antigua and Barbuda',
  'TO': 'Tonga',
  'IS': 'Iceland',
  'TC': 'Turks and Caicos Islands',
  'UZ': 'Uzbekistan',
  'XK': 'Kosovo',
  'IL': 'Israel',
  'ET': 'Ethiopia',
  'IT': 'Italy',
  'UG': 'Uganda',
  'HT': 'Haiti',
  'LK': 'Sri Lanka',
  'ST': 'São Tomé and Príncipe',
  'TH': 'Thailand',
  'SV': 'El Salvador',
  'LS': 'Lesotho',
  'RS': 'Serbia',
  'SZ': 'Swaziland',
  'TT': 'Trinidad and Tobago',
  'BT': 'Bhutan',
  'ME': 'Montenegro',
  'GR': 'Greece',
  'SD': 'Sudan',
  'CY': 'Cyprus',
  'ZM': 'Zambia',
  'SL': 'Sierra Leone',
  'UY': 'Uruguay',
  'HR': 'Croatia',
  'VC': 'Saint Vincent and the Grenadines',
  'QA': 'Qatar',
  'BE': 'Belgium',
  'SE': 'Sweden',
  'US': 'United States of America',
  'TG': 'Togo',
  'SI': 'Slovenia',
  'FI': 'Finland',
  'SK': 'Slovakia',
  'PY': 'Paraguay',
  'ML': 'Mali',
  'SA': 'Saudi Arabia',
  'GS': 'South Georgia and South Sandwich Islands',
  'SN': 'Senegal',
  'BY': 'Belarus',
  'KR': 'South Korea',
  'NP': 'Nepal',
  'NU': 'Niue',
  'IR': 'Iran',
  'CR': 'Costa Rica',
  'GL': 'Greenland',
  'DJ': 'Djibouti',
  'LY': 'Libya',
  'NI': 'Nicaragua',
  'AF': 'Afghanistan',
  'NE': 'Niger',
  'KE': 'Kenya',
  'NZ': 'New Zealand',
  'HU': 'Hungary',
  'MV': 'Maldives',
  'BS': 'The Bahamas',
  'GD': 'Grenada',
  'BZ': 'Belize',
  'BW': 'Botswana',
  'LT': 'Lithuania',
  'JP': 'Japan',
  'IM': 'Isle of Man',
  'NG': 'Nigeria',
  'MX': 'Mexico',
  'CN': 'China',
  'CO': 'Colombia',
  'EG': 'Egypt',
  'NL': 'Netherlands',
  'DZ': 'Algeria',
  'GT': 'Guatemala',
  'SC': 'Seychelles',
  'VU': 'Vanuatu',
  'KG': 'Kyrgyzstan',
  'AL': 'Albania',
  'CU': 'Cuba',
  'UA': 'Ukraine',
  'MH': 'Marshall Islands',
  'SR': 'Suriname',
  'PG': 'Papua New Guinea',
  'CZ': 'Czech Republic',
  'LC': 'Saint Lucia',
  'AT': 'Austria',
  'BR': 'Brazil',
  'MM': 'Myanmar',
  'PH': 'Philippines',
  'KZ': 'Kazakhstan',
  'MY': 'Malaysia',
  'DE': 'Germany',
  'CK': 'Cook Islands',
  'CL': 'Chile',
  'DO': 'Dominican Republic',
  'BA': 'Bosnia and Herzegovina',
  'ES': 'Spain',
  'LR': 'Liberia',
  'YE': 'Yemen',
  'KH': 'Cambodia',
  'VN': 'Vietnam',
  'NA': 'Namibia',
  'ID': 'Indonesia',
  'MK': 'Macedonia',
  'FO': 'Faroe Islands',
  'TK': 'Tokelau',
  'TN': 'Tunisia',
  'PL': 'Poland',
  'BG': 'Bulgaria',
  'MD': 'Moldova',
  'HN': 'Honduras',
  'TW': 'Taiwan',
  'AE': 'United Arab Emirates',
  'CM': 'Cameroon',
  'CV': 'Cape Verde',
  'TL': 'East Timor',
  'RO': 'Romania',
  'AD': 'Andorra',
  'AQ': 'Antarctica',
  'BB': 'Barbados',
  'DM': 'Dominica',
  'GG': 'Guernsey',
  'GI': 'Gibraltar',
  'GM': 'Gambia',
  'KM': 'Comoros',
  'KN': 'Saint Kitts and Nevis',
  'LI': 'Liechtenstein',
  'MC': 'Monaco',
  'MU': 'Mauritius',
  'NC': 'New Caledonia',
  'PR': 'Puerto Rico',
  'PS': 'West Bank',
  'SG': 'Singapore',
  'TF': 'Fr. S. and Antarctic Lands',
  'SM': 'San Marino',
  'RE': 'Reunion',
  'VG': 'British Virgin Islands',
  'MF': 'Saint-Martin',
  'YT': 'Mayotte',
  'MS': 'Montserrat',
  'NR': 'Nauru'
}

latitude_dict = {
  0: {'MV', 'ID', 'CG', 'VE', 'ST', 'KI', 'CD', 'TZ', 'PG', 'BR', 'FM', 'SO', 'EC', 'UG', 'GA', 'KE', 'PE', 'CO'},
  1: {'SR', 'KI', 'MV', 'ID', 'CG', 'VE', 'ST', 'CD', 'MY', 'BR', 'FM', 'SO', 'EC', 'UG', 'GA', 'KE', 'GY', 'CM', 'GQ', 'CO', 'SG'},
  2: {'SR', 'MV', 'ID', 'CG', 'VE', 'MY', 'KI', 'CD', 'FR', 'ST', 'BR', 'FM', 'SO', 'EC', 'GQ', 'GA', 'KE', 'UG', 'GY', 'CM', 'CO', 'SG'},
  3: {'FR', 'FM', 'SO', 'SS', 'CF', 'GY', 'SR', 'VE', 'BR', 'GQ', 'CO', 'MY', 'KI', 'GA', 'KE', 'MV', 'ID', 'CG', 'CD', 'ET', 'UG', 'CM'},
  4: {'FR', 'FM', 'SO', 'SS', 'CF', 'GY', 'SR', 'CI', 'VE', 'BR', 'PH', 'NG', 'CO', 'MY', 'BN', 'KI', 'GH', 'LR', 'KE', 'MV', 'ID', 'CG', 'CD', 'ET', 'UG', 'CM'},
  5: {'FR', 'LK', 'FM', 'SO', 'SS', 'CF', 'GY', 'MH', 'SR', 'CI', 'VE', 'BR', 'NG', 'PH', 'CO', 'MY', 'BN', 'GH', 'KE', 'MV', 'ID', 'CD', 'ET', 'UG', 'LR', 'CM'},
  6: {'TH', 'FR', 'LK', 'IN', 'FM', 'SO', 'SS', 'CF', 'GY', 'MH', 'SR', 'CI', 'VE', 'US', 'TG', 'NG', 'PH', 'CO', 'BJ', 'MY', 'BN', 'GH', 'MV', 'ID', 'CD', 'ET', 'SL', 'LR', 'CM'},
  7: {'TH', 'LK', 'IN', 'FM', 'SO', 'SS', 'CF', 'GY', 'MH', 'SR', 'CI', 'VE', 'TG', 'PA', 'NG', 'PH', 'CO', 'BJ', 'MY', 'GH', 'CR', 'GN', 'MV', 'ID', 'ET', 'SL', 'LR', 'TD', 'CM'},
  8: {'TH', 'LK', 'IN', 'FM', 'SO', 'SD', 'SS', 'CF', 'GY', 'MH', 'CI', 'VE', 'TG', 'PA', 'PH', 'NG', 'CO', 'BJ', 'MY', 'GH', 'CR', 'GN', 'VN', 'MV', 'ET', 'SL', 'LR', 'TD', 'CM'},
  9: {'TH', 'LK', 'IN', 'TT', 'FM', 'SD', 'SO', 'SS', 'CF', 'BF', 'GY', 'MH', 'CI', 'VE', 'TG', 'PA', 'MM', 'PH', 'NG', 'CO', 'BJ', 'GH', 'KH', 'CR', 'LR', 'GN', 'VN', 'ET', 'SL', 'CM', 'TD'},
  10: {'TH', 'LK', 'IN', 'TT', 'FM', 'SD', 'SO', 'SS', 'CF', 'BF', 'MH', 'GW', 'CI', 'VE', 'TG', 'PA', 'ML', 'MM', 'PH', 'NG', 'CO', 'BJ', 'GH', 'KH', 'CR', 'DJ', 'GN', 'NI', 'VN', 'ET', 'SL', 'CM', 'TD'},
  11: {'TH', 'LK', 'IN', 'TT', 'FM', 'SD', 'SO', 'SS', 'CF', 'BF', 'MH', 'GW', 'CI', 'VE', 'TG', 'ML', 'MM', 'PH', 'NG', 'CO', 'BJ', 'GH', 'KH', 'CR', 'DJ', 'GN', 'NI', 'YE', 'VN', 'GD', 'ET', 'CM', 'TD', 'NL'},
  12: {'TH', 'IN', 'TT', 'SD', 'SO', 'SS', 'BF', 'VC', 'GW', 'MH', 'VE', 'ML', 'SN', 'MM', 'PH', 'NG', 'CO', 'BJ', 'KH', 'GH', 'DJ', 'GN', 'NI', 'YE', 'NE', 'VN', 'ER', 'GD', 'ET', 'CM', 'TD', 'NL', 'BB'},
  13: {'TH', 'GT', 'IN', 'SV', 'SD', 'SO', 'SS', 'BF', 'VC', 'GW', 'VE', 'LC', 'ML', 'LA', 'SN', 'MM', 'NG', 'PH', 'CO', 'BJ', 'KH', 'DJ', 'HN', 'GN', 'NI', 'NE', 'YE', 'VN', 'ER', 'GD', 'ET', 'CM', 'TD', 'NL', 'BB', 'GM'},
  14: {'TH', 'GT', 'FR', 'IN', 'SV', 'SD', 'BF', 'VC', 'US', 'LC', 'ML', 'LA', 'SN', 'MM', 'PH', 'NG', 'CO', 'KH', 'HN', 'NI', 'YE', 'NE', 'VN', 'ER', 'MR', 'ET', 'TD', 'CV', 'BB', 'DM', 'GM'},
  15: {'TH', 'GT', 'FR', 'IN', 'SV', 'SD', 'BF', 'LC', 'ML', 'LA', 'SN', 'MM', 'PH', 'CO', 'KH', 'HN', 'NI', 'NE', 'YE', 'VN', 'ER', 'BZ', 'MR', 'ET', 'MX', 'CN', 'TD', 'CV', 'DM'},
  16: {'TH', 'GT', 'FR', 'IN', 'SD', 'OM', 'US', 'JM', 'ML', 'SA', 'LA', 'SN', 'MM', 'PH', 'HN', 'YE', 'NE', 'VN', 'ER', 'AG', 'BZ', 'MR', 'MX', 'CN', 'TD', 'CV', 'DM'},
  17: {'TH', 'GT', 'FR', 'IN', 'SD', 'OM', 'JM', 'ML', 'SA', 'LA', 'SN', 'MM', 'PH', 'DO', 'HN', 'HT', 'YE', 'NE', 'VN', 'ER', 'AG', 'BZ', 'MR', 'MX', 'CN', 'TD', 'NL', 'CV', 'PR'},
  18: {'TH', 'GT', 'IN', 'SD', 'OM', 'US', 'JM', 'ML', 'SA', 'LA', 'MM', 'PH', 'DO', 'HT', 'NE', 'YE', 'VN', 'ER', 'AG', 'BZ', 'MR', 'MX', 'TD', 'NL', 'CV', 'PR', 'VG'},
  19: {'TH', 'DZ', 'IN', 'SD', 'CU', 'OM', 'US', 'JM', 'ML', 'SA', 'LA', 'MM', 'PH', 'DO', 'LY', 'HT', 'NE', 'YE', 'VN', 'BZ', 'MR', 'MX', 'CN', 'TD', 'NL', 'PR', 'VG'},
  20: {'TH', 'DZ', 'IN', 'SD', 'CU', 'OM', 'US', 'ML', 'SA', 'LA', 'MM', 'PH', 'DO', 'LY', 'HT', 'NE', 'VN', 'BS', 'MR', 'MX', 'CN', 'TD'},
  21: {'TH', 'DZ', 'EH', 'IN', 'MA', 'SD', 'CU', 'OM', 'US', 'BD', 'ML', 'SA', 'LA', 'MM', 'PH', 'DO', 'LY', 'HT', 'NE', 'VN', 'BS', 'TC', 'MR', 'MX', 'CN', 'TD', 'EG', 'TW'},
  22: {'DZ', 'EH', 'IN', 'MA', 'SD', 'CU', 'OM', 'US', 'BD', 'ML', 'SA', 'LA', 'MM', 'PH', 'DO', 'LY', 'NE', 'VN', 'BS', 'TC', 'MR', 'AE', 'MX', 'CN', 'TD', 'EG', 'TW'},
  23: {'DZ', 'EH', 'IN', 'MA', 'SD', 'CU', 'OM', 'PK', 'US', 'BD', 'ML', 'SA', 'LA', 'MM', 'LY', 'NE', 'VN', 'BS', 'TC', 'MR', 'JP', 'AE', 'MX', 'CN', 'TD', 'EG', 'TW'},
  24: {'DZ', 'EH', 'IN', 'MA', 'CU', 'OM', 'QA', 'PK', 'US', 'BD', 'ML', 'SA', 'MM', 'IR', 'LY', 'NE', 'VN', 'BS', 'MR', 'JP', 'AE', 'MX', 'CN', 'TD', 'EG', 'TW'},
  25: {'DZ', 'EH', 'IN', 'MA', 'OM', 'QA', 'PK', 'US', 'BD', 'ML', 'SA', 'MM', 'IR', 'LY', 'BS', 'MR', 'JP', 'AE', 'MX', 'CN', 'EG', 'TW'},
  26: {'DZ', 'EH', 'IN', 'BT', 'MA', 'QA', 'PK', 'US', 'BD', 'ML', 'SA', 'MM', 'NP', 'IR', 'LY', 'BS', 'MR', 'JP', 'AE', 'MX', 'CN', 'EG', 'TW'},
  27: {'DZ', 'EH', 'IN', 'BT', 'MA', 'QA', 'PK', 'US', 'BD', 'SA', 'MM', 'NP', 'IR', 'ES', 'LY', 'BS', 'MR', 'JP', 'AE', 'MX', 'CN', 'EG', 'TW'},
  28: {'PK', 'DZ', 'BS', 'NP', 'IN', 'US', 'IR', 'KW', 'JP', 'ES', 'BT', 'MA', 'LY', 'SA', 'MX', 'CN', 'MM', 'EG'},
  29: {'DZ', 'IN', 'BT', 'MA', 'QA', 'PK', 'US', 'SA', 'PT', 'MM', 'IQ', 'NP', 'IR', 'KW', 'ES', 'LY', 'AF', 'JO', 'JP', 'IL', 'MX', 'CN', 'EG'},
  30: {'DZ', 'IN', 'MA', 'QA', 'PK', 'US', 'PT', 'SA', 'IQ', 'NP', 'IR', 'KW', 'ES', 'LY', 'AF', 'JO', 'JP', 'TN', 'IL', 'MX', 'CN', 'EG'},
  31: {'QA', 'PK', 'DZ', 'NP', 'IN', 'US', 'IR', 'TN', 'JP', 'IL', 'EG', 'PS', 'MA', 'LY', 'SA', 'PT', 'AF', 'MX', 'CN', 'JO', 'IQ', 'PS'},
  32: {'PK', 'DZ', 'IN', 'US', 'IR', 'TN', 'JP', 'IL', 'EG', 'SY', 'PS', 'MA', 'LY', 'SA', 'PT', 'AF', 'MX', 'CN', 'JO', 'IQ', 'PS'},
  33: {'PK', 'DZ', 'KR', 'LB', 'IN', 'US', 'IR', 'TN', 'JP', 'IL', 'SY', 'PS', 'LY', 'MA', 'PT', 'SA', 'AF', 'CN', 'JO', 'IQ', 'PS'},
  34: {'PK', 'DZ', 'KR', 'LB', 'IN', 'US', 'IR', 'TN', 'JP', 'IL', 'SY', 'MA', 'GR', 'LY', 'CY', 'AF', 'PT', 'CN', 'IQ'},
  35: {'PK', 'DZ', 'KR', 'LB', 'IN', 'US', 'IR', 'TN', 'JP', 'MT', 'ES', 'SY', 'IT', 'MA', 'GR', 'CY', 'AF', 'CN', 'TR', 'IQ', 'TM', 'GI'},
  36: {'DZ', 'IN', 'MA', 'GR', 'CY', 'TR', 'PK', 'US', 'PT', 'TJ', 'IQ', 'KR', 'IR', 'ES', 'TM', 'AF', 'TN', 'JP', 'MT', 'IT', 'SY', 'CN', 'GI'},
  37: {'DZ', 'PK', 'KR', 'US', 'UZ', 'IR', 'TN', 'JP', 'MT', 'ES', 'IT', 'SY', 'KP', 'PT', 'GR', 'TJ', 'TM', 'CN', 'TR', 'IQ', 'AF', 'GI'},
  38: {'DZ', 'KR', 'UZ', 'US', 'IR', 'JP', 'TN', 'ES', 'IT', 'KP', 'SY', 'PT', 'GR', 'TJ', 'TM', 'CN', 'TR', 'AZ', 'IQ', 'AF'},
  39: {'AL', 'KR', 'UZ', 'US', 'IR', 'AF', 'JP', 'ES', 'IT', 'KP', 'PT', 'GR', 'TJ', 'TM', 'KG', 'CN', 'TR', 'AZ', 'AM'},
  40: {'MK', 'AL', 'UZ', 'US', 'IR', 'JP', 'ES', 'IT', 'KP', 'GR', 'PT', 'TJ', 'TM', 'KG', 'CN', 'TR', 'AZ', 'AM'},
  41: {'FR', 'ME', 'GR', 'KG', 'TR', 'VA', 'AL', 'UZ', 'US', 'KP', 'PT', 'TJ', 'AM', 'GE', 'MK', 'KZ', 'MN', 'ES', 'TM', 'JP', 'IT', 'BG', 'CN', 'AZ', 'AD'},
  42: {'FR', 'ME', 'RS', 'GR', 'KG', 'TR', 'HR', 'VA', 'AL', 'US', 'UZ', 'CA', 'KP', 'PT', 'GE', 'AM', 'MK', 'MN', 'KZ', 'ES', 'BA', 'TM', 'RU', 'JP', 'XK', 'IT', 'BG', 'CN', 'AZ', 'AD'},
  43: {'FR', 'ME', 'RS', 'KG', 'TR', 'HR', 'VA', 'AL', 'UZ', 'US', 'CA', 'KP', 'GE', 'KZ', 'MN', 'MK', 'ES', 'BA', 'TM', 'RU', 'JP', 'XK', 'IT', 'BG', 'CN', 'RO', 'AD', 'MC'},
  44: {'KZ', 'MN', 'FR', 'ME', 'UZ', 'US', 'CA', 'JP', 'RS', 'BA', 'XK', 'IT', 'BG', 'ES', 'GE', 'RO', 'KG', 'CN', 'UA', 'HR', 'RU', 'MC', 'SM'},
  45: {'KZ', 'MN', 'FR', 'UZ', 'US', 'SI', 'CA', 'JP', 'RS', 'BA', 'CH', 'IT', 'BG', 'HU', 'RO', 'CN', 'UA', 'HR', 'RU'},
  46: {'KZ', 'MN', 'HR', 'FR', 'US', 'UZ', 'SI', 'CA', 'AT', 'CH', 'RS', 'JP', 'IT', 'BA', 'MD', 'RO', 'CN', 'UA', 'HU', 'RU'},
  47: {'KZ', 'MN', 'HR', 'FR', 'DE', 'US', 'SI', 'CA', 'AT', 'CH', 'RS', 'IT', 'MD', 'SK', 'RO', 'CN', 'UA', 'HU', 'RU', 'LI'},
  48: {'KZ', 'MN', 'FR', 'DE', 'CZ', 'US', 'JE', 'CA', 'AT', 'CH', 'IT', 'MD', 'SK', 'RO', 'CN', 'UA', 'HU', 'RU'},
  49: {'KZ', 'MN', 'GB', 'BE', 'FR', 'DE', 'JE', 'CZ', 'US', 'LU', 'CA', 'AT', 'PL', 'MD', 'SK', 'RO', 'CN', 'UA', 'HU', 'RU', 'GG'},
  50: {'KZ', 'GB', 'BE', 'MN', 'FR', 'DE', 'CZ', 'JE', 'LU', 'CA', 'AT', 'PL', 'SK', 'CN', 'UA', 'RU', 'GG'},
  51: {'KZ', 'GB', 'BE', 'MN', 'FR', 'DE', 'CZ', 'LU', 'CA', 'PL', 'IE', 'NL', 'CN', 'UA', 'RU', 'BY'},
  52: {'KZ', 'GB', 'MN', 'BE', 'FR', 'DE', 'CZ', 'US', 'CA', 'PL', 'IE', 'NL', 'CN', 'UA', 'RU', 'BY'},
  53: {'KZ', 'GB', 'MN', 'DE', 'US', 'LT', 'CA', 'IM', 'PL', 'IE', 'NL', 'CN', 'UA', 'RU', 'BY'},
  54: {'KZ', 'GB', 'DE', 'US', 'LT', 'CA', 'IM', 'PL', 'IE', 'NL', 'DK', 'RU', 'BY'},
  55: {'KZ', 'GB', 'SE', 'DE', 'US', 'LT', 'CA', 'IM', 'PL', 'IE', 'DK', 'LV', 'RU', 'BY'},
  56: {'KZ', 'GB', 'SE', 'DE', 'US', 'LT', 'CA', 'PL', 'IE', 'DK', 'LV', 'RU', 'BY'},
  57: {'GB', 'SE', 'US', 'LT', 'CA', 'EE', 'DK', 'NO', 'LV', 'RU', 'BY'},
  58: {'GB', 'SE', 'US', 'CA', 'EE', 'DK', 'NO', 'LV', 'RU'},
  59: {'GB', 'SE', 'US', 'CA', 'FI', 'GL', 'EE', 'NO', 'LV', 'RU'},
  60: {'GB', 'SE', 'US', 'CA', 'FI', 'GL', 'EE', 'NO', 'RU'},
  61: {'GB', 'SE', 'FO', 'US', 'CA', 'FI', 'GL', 'NO', 'RU'},
  62: {'GB', 'SE', 'FO', 'US', 'CA', 'FI', 'GL', 'NO', 'RU'},
  63: {'SE', 'FO', 'US', 'IS', 'CA', 'FI', 'GL', 'NO', 'RU'},
  64: {'SE', 'US', 'IS', 'CA', 'FI', 'GL', 'NO', 'RU'},
  65: {'SE', 'US', 'IS', 'CA', 'FI', 'GL', 'NO', 'RU'},
  66: {'SE', 'US', 'IS', 'CA', 'FI', 'GL', 'NO', 'RU'},
  67: {'SE', 'US', 'IS', 'CA', 'FI', 'GL', 'NO', 'RU'},
  68: {'SE', 'US', 'IS', 'CA', 'FI', 'GL', 'NO', 'RU'},
  69: {'SE', 'US', 'CA', 'FI', 'GL', 'NO', 'RU'},
  70: {'US', 'CA', 'FI', 'GL', 'NO', 'RU'},
  71: {'US', 'CA', 'FI', 'GL', 'NO', 'RU'},
  72: {'NO', 'CA', 'GL', 'RU'},
  73: {'CA', 'GL', 'RU'},
  74: {'CA', 'GL', 'RU'},
  75: {'CA', 'GL', 'RU'},
  76: {'NO', 'CA', 'GL', 'RU'},
  77: {'NO', 'CA', 'GL', 'RU'},
  78: {'NO', 'CA', 'GL', 'RU'},
  79: {'NO', 'CA', 'GL', 'RU'},
  80: {'NO', 'CA', 'GL', 'RU'},
  81: {'NO', 'CA', 'GL', 'RU'},
  82: {'NO', 'CA', 'GL', 'RU'},
  83: {'CA', 'GL'},
  -90: {'AQ'},
  -89: {'AQ'},
  -88: {'AQ'},
  -87: {'AQ'},
  -86: {'AQ'},
  -85: {'AQ'},
  -84: {'AQ'},
  -83: {'AQ'},
  -82: {'AQ'},
  -81: {'AQ'},
  -80: {'AQ'},
  -79: {'AQ'},
  -78: {'AQ'},
  -77: {'AQ'},
  -76: {'AQ'},
  -75: {'AQ'},
  -74: {'AQ'},
  -73: {'AQ'},
  -72: {'AQ'},
  -71: {'AQ'},
  -70: {'AQ'},
  -69: {'AQ'},
  -68: {'AQ'},
  -67: {'AQ'},
  -66: {'AQ'},
  -65: {'AQ'},
  -64: {'AQ'},
  -63: {'AQ'},
  -62: {'AQ'},
  -61: {'AQ'},
  -60: {'AQ'},
  -59: {'GS'},
  -58: {'GS'},
  -57: {'CL', 'GS'},
  -56: {'AR', 'CL', 'GS'},
  -55: {'AR', 'CL', 'GS'},
  -54: {'FK', 'AR', 'CL', 'GS'},
  -53: {'FK', 'AR', 'CL', 'AU', 'GS'},
  -52: {'FK', 'AR', 'CL', 'NZ'},
  -51: {'FR', 'FK', 'AR', 'CL', 'NZ', 'TF'},
  -50: {'CL', 'FK', 'AR', 'FR', 'NZ', 'TF'},
  -49: {'CL', 'AR', 'FR', 'TF'},
  -48: {'FR', 'NZ', 'AR', 'CL', 'ZA', 'TF'},
  -47: {'FR', 'NZ', 'AR', 'CL', 'ZA'},
  -46: {'CL', 'NZ', 'AR', 'FR', 'ZA'},
  -45: {'FR', 'NZ', 'AR', 'CL'},
  -44: {'NZ', 'AR', 'CL', 'AU'},
  -43: {'NZ', 'AR', 'CL', 'AU'},
  -42: {'NZ', 'AR', 'CL', 'AU'},
  -41: {'NZ', 'AR', 'CL', 'AU'},
  -40: {'NZ', 'AR', 'CL', 'AU'},
  -39: {'NZ', 'AR', 'CL', 'AU'},
  -38: {'NZ', 'AR', 'CL', 'AU'},
  -37: {'NZ', 'AR', 'CL', 'AU'},
  -36: {'CL', 'ZA', 'UY', 'AU', 'NZ', 'AR'},
  -35: {'CL', 'ZA', 'UY', 'AU', 'NZ', 'AR'},
  -34: {'CL', 'ZA', 'UY', 'AU', 'NZ', 'AR'},
  -33: {'CL', 'ZA', 'NZ', 'BR', 'AU', 'UY', 'AR'},
  -32: {'CL', 'ZA', 'BR', 'AU', 'UY', 'AR'},
  -31: {'LS', 'CL', 'ZA', 'BR', 'AU', 'UY', 'AR'},
  -30: {'LS', 'CL', 'ZA', 'BR', 'AU', 'UY', 'AR'},
  -29: {'NA', 'LS', 'CL', 'ZA', 'BR', 'AU', 'AR'},
  -28: {'NA', 'LS', 'CL', 'ZA', 'SZ', 'PY', 'BR', 'AU', 'AR'},
  -27: {'NA', 'MZ', 'BW', 'CL', 'ZA', 'SZ', 'PY', 'BR', 'AU', 'AR'},
  -26: {'NA', 'MZ', 'BW', 'CL', 'ZA', 'SZ', 'PY', 'BR', 'AU', 'AR', 'MG'},
  -25: {'NA', 'MZ', 'BW', 'TO', 'CL', 'ZA', 'SZ', 'PY', 'BR', 'AU', 'AR', 'MG'},
  -24: {'NA', 'FR', 'MZ', 'BW', 'TO', 'CL', 'ZA', 'PY', 'BR', 'AU', 'AR', 'MG'},
  -23: {'NA', 'FR', 'MZ', 'BW', 'TO', 'CK', 'CL', 'ZA', 'ZW', 'PY', 'BR', 'AU', 'BO', 'AR', 'MG', 'NC'},
  -22: {'NA', 'FR', 'MZ', 'BW', 'TO', 'CK', 'CL', 'ZA', 'FJ', 'ZW', 'PY', 'BR', 'BO', 'AU', 'AR', 'MG', 'NC', 'RE'},
  -21: {'NA', 'FR', 'MZ', 'BW', 'TO', 'CK', 'VU', 'CL', 'FJ', 'AR', 'ZW', 'PY', 'BR', 'BO', 'AU', 'MG', 'MU', 'NC', 'RE'},
  -20: {'NA', 'FR', 'MZ', 'BW', 'TO', 'CK', 'VU', 'NU', 'CL', 'FJ', 'ZW', 'PY', 'BR', 'BO', 'AU', 'PE', 'MG', 'MU', 'NC', 'RE'},
  -19: {'NA', 'FR', 'MZ', 'TO', 'NU', 'CK', 'BW', 'VU', 'CL', 'FJ', 'ZW', 'PY', 'BR', 'BO', 'AU', 'PE', 'MG', 'MU', 'NC'},
  -18: {'NA', 'FR', 'MZ', 'BW', 'VU', 'CK', 'AO', 'TO', 'NU', 'CL', 'FJ', 'ZW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG', 'KN'},
  -17: {'NA', 'FR', 'MZ', 'TO', 'VU', 'BW', 'AO', 'CK', 'FJ', 'ZW', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG', 'KN'},
  -16: {'NA', 'FR', 'MZ', 'TO', 'VU', 'AO', 'FJ', 'ZW', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG'},
  -15: {'FR', 'WS', 'MZ', 'TO', 'VU', 'AO', 'FJ', 'MW', 'ZW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG'},
  -14: {'WS', 'FR', 'MZ', 'VU', 'CD', 'AO', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG'},
  -13: {'FR', 'WS', 'MZ', 'CD', 'VU', 'AO', 'SB', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG', 'KM'},
  -12: {'ID', 'PG', 'TZ', 'MZ', 'FR', 'CD', 'CK', 'SB', 'AO', 'VU', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG', 'KM'},
  -11: {'KI', 'ID', 'PG', 'TZ', 'MZ', 'US', 'CD', 'CK', 'AO', 'SB', 'FR', 'SC', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'MG', 'KM'},
  -10: {'KI', 'ID', 'PG', 'FR', 'TZ', 'SC', 'CD', 'CK', 'AO', 'SB', 'TK', 'MZ', 'MW', 'BR', 'BO', 'AU', 'PE', 'ZM', 'TL'},
  -9: {'KI', 'ID', 'PG', 'FR', 'TZ', 'SC', 'TK', 'CK', 'AO', 'CD', 'SB', 'MW', 'BR', 'BO', 'PE', 'ZM', 'TL'},
  -8: {'ID', 'PG', 'TZ', 'FR', 'CD', 'TK', 'SB', 'AO', 'CK', 'BR', 'PE', 'ZM', 'TL'},
  -7: {'ID', 'PG', 'TZ', 'SC', 'CD', 'SB', 'AO', 'BR', 'PE'},
  -6: {'ID', 'PG', 'SC', 'TZ', 'CG', 'CD', 'AO', 'SB', 'BR', 'PE'},
  -5: {'KI', 'ID', 'PG', 'CG', 'TZ', 'BI', 'CD', 'SC', 'AO', 'BR', 'PE', 'EC', 'GA', 'KE', 'CO'},
  -4: {'KI', 'ID', 'PG', 'CG', 'TZ', 'BI', 'CD', 'BR', 'PE', 'EC', 'GA', 'KE', 'CO'},
  -3: {'KI', 'ID', 'PG', 'CG', 'TZ', 'BI', 'CD', 'RW', 'BR', 'PE', 'EC', 'GA', 'KE', 'CO'},
  -2: {'KI', 'ID', 'PG', 'CG', 'TZ', 'RW', 'CD', 'BI', 'BR', 'PE', 'EC', 'UG', 'GA', 'KE', 'SO', 'CO'},
  -1: {'MV', 'ID', 'PG', 'CG', 'TZ', 'RW', 'CD', 'BR', 'PE', 'EC', 'UG', 'GA', 'KE', 'SO', 'CO'}
}

longitude_dict = {
  0: {'AQ', 'GB', 'DZ', 'BJ', 'FR', 'GH', 'TG', 'ES', 'ML', 'NE', 'BF'},
  1: {'AQ', 'BJ', 'DZ', 'GB', 'FR', 'GH', 'TG', 'ES', 'ML', 'NE', 'BF', 'AD'},
  2: {'AQ', 'BJ', 'DZ', 'BE', 'FR', 'GB', 'GH', 'TG', 'ES', 'ML', 'NE', 'BF', 'NG', 'AD'},
  3: {'AQ', 'BJ', 'DZ', 'BE', 'FR', 'ES', 'ML', 'NE', 'BF', 'NG', 'NL', 'AD'},
  4: {'AQ', 'BJ', 'DZ', 'BE', 'FR', 'ES', 'NO', 'ML', 'NE', 'NG', 'NL'},
  5: {'AQ', 'DZ', 'BE', 'FR', 'DE', 'LU', 'ES', 'NE', 'ML', 'NO', 'NG', 'NL'},
  6: {'AQ', 'DZ', 'BE', 'FR', 'DE', 'ST', 'LU', 'CH', 'NO', 'IT', 'NE', 'NG', 'NL'},
  7: {'AQ', 'DZ', 'FR', 'DE', 'ST', 'LU', 'TN', 'CH', 'IT', 'NE', 'DK', 'NO', 'NG', 'NL', 'MC'},
  8: {'AQ', 'DZ', 'FR', 'DE', 'ST', 'TN', 'CH', 'GA', 'IT', 'NE', 'DK', 'NO', 'CM', 'NG', 'NL', 'MC'},
  9: {'AQ', 'DZ', 'FR', 'DE', 'TN', 'AT', 'CH', 'GA', 'IT', 'NE', 'LY', 'DK', 'GQ', 'NO', 'CM', 'NG', 'LI'},
  10: {'AQ', 'DZ', 'SE', 'FR', 'DE', 'TN', 'AT', 'CH', 'GA', 'IT', 'NE', 'LY', 'DK', 'GQ', 'NO', 'CM', 'NG', 'LI'},
  11: {'AQ', 'DZ', 'SE', 'NA', 'DE', 'CG', 'VA', 'AO', 'TN', 'AT', 'GA', 'IT', 'NE', 'LY', 'DK', 'GQ', 'NO', 'CM', 'NG'},
  12: {'AQ', 'NA', 'VA', 'SE', 'CG', 'DE', 'CZ', 'CD', 'DZ', 'AO', 'TN', 'AT', 'GA', 'IT', 'NE', 'LY', 'DK', 'GQ', 'NO', 'CM', 'NG', 'SM'},
  13: {'AQ', 'NA', 'SE', 'CG', 'DE', 'CZ', 'VA', 'CD', 'SI', 'AO', 'AT', 'MT', 'GA', 'IT', 'NE', 'LY', 'DK', 'NO', 'CM', 'TD', 'HR', 'NG', 'SM'},
  14: {'AQ', 'CF', 'HR', 'SE', 'SI', 'AT', 'DK', 'NG', 'DE', 'CZ', 'LY', 'GA', 'NE', 'NO', 'NA', 'CG', 'CD', 'AO', 'MT', 'PL', 'IT', 'CM', 'TD'},
  15: {'AQ', 'CF', 'HR', 'SE', 'SI', 'AT', 'DK', 'NG', 'DE', 'CZ', 'BA', 'LY', 'GA', 'NE', 'NO', 'NA', 'CG', 'CD', 'AO', 'MT', 'PL', 'IT', 'CM', 'TD'},
  16: {'AQ', 'NA', 'SE', 'CG', 'CZ', 'CD', 'SI', 'AO', 'AT', 'ZA', 'BA', 'PL', 'IT', 'HU', 'LY', 'NE', 'DK', 'CF', 'NO', 'CM', 'TD', 'HR'},
  17: {'AQ', 'HR', 'NA', 'SE', 'CG', 'CZ', 'CD', 'AO', 'AT', 'ZA', 'BA', 'PL', 'IT', 'LY', 'SK', 'CF', 'NO', 'CM', 'TD', 'HU'},
  18: {'AQ', 'HR', 'NA', 'SE', 'CG', 'CZ', 'ME', 'CD', 'AO', 'AT', 'ZA', 'BA', 'PL', 'IT', 'LY', 'SK', 'CF', 'NO', 'TD', 'HU'},
  19: {'AQ', 'ME', 'RS', 'CF', 'HR', 'SE', 'AL', 'FI', 'SK', 'CZ', 'BA', 'LY', 'NO', 'HU', 'NA', 'CG', 'BW', 'CD', 'AO', 'ZA', 'PL', 'IT', 'TD'},
  20: {'AQ', 'ME', 'RS', 'GR', 'CF', 'HR', 'SE', 'AL', 'FI', 'SK', 'LV', 'MK', 'BA', 'LY', 'NO', 'HU', 'RU', 'NA', 'BW', 'CD', 'AO', 'LT', 'XK', 'ZA', 'PL', 'TD', 'RO'},
  21: {'AQ', 'ME', 'RS', 'GR', 'SD', 'CF', 'SE', 'AL', 'FI', 'EE', 'SK', 'LV', 'MK', 'LY', 'NO', 'HU', 'RU', 'NA', 'BW', 'CD', 'AO', 'LT', 'XK', 'ZA', 'PL', 'TD', 'RO'},
  22: {'AQ', 'RS', 'GR', 'SD', 'CF', 'ZM', 'UA', 'SE', 'FI', 'EE', 'SK', 'LV', 'MK', 'LY', 'NO', 'HU', 'RU', 'NA', 'BW', 'CD', 'AO', 'LT', 'XK', 'ZA', 'PL', 'BG', 'TD', 'RO'},
  23: {'AQ', 'RS', 'GR', 'SD', 'CF', 'ZM', 'UA', 'SE', 'FI', 'EE', 'SK', 'LV', 'BY', 'MK', 'LY', 'NO', 'HU', 'NA', 'BW', 'CD', 'LT', 'AO', 'ZA', 'PL', 'BG', 'TD', 'RO'},
  24: {'AQ', 'GR', 'SD', 'SS', 'CF', 'ZM', 'UA', 'SE', 'FI', 'EE', 'LV', 'BY', 'LY', 'NO', 'NA', 'BW', 'CD', 'LT', 'AO', 'ZA', 'PL', 'BG', 'TD', 'EG', 'RO'},
  25: {'AQ', 'GR', 'SD', 'SS', 'CF', 'ZM', 'TR', 'UA', 'SE', 'FI', 'EE', 'ZW', 'LV', 'BY', 'LY', 'NO', 'NA', 'BW', 'CD', 'LT', 'AO', 'ZA', 'BG', 'EG', 'RO'},
  26: {'AQ', 'SS', 'UA', 'BW', 'CD', 'LT', 'FI', 'ZA', 'EE', 'ZW', 'BG', 'NO', 'LY', 'GR', 'SD', 'ZM', 'CF', 'TR', 'LV', 'EG', 'RO', 'BY'},
  27: {'AQ', 'LS', 'GR', 'SD', 'SS', 'ZM', 'CF', 'UA', 'TR', 'FI', 'EE', 'ZW', 'LV', 'BY', 'NO', 'RU', 'BW', 'CD', 'LT', 'ZA', 'BG', 'MD', 'EG', 'RO'},
  28: {'AQ', 'UA', 'BW', 'CD', 'LS', 'FI', 'ZA', 'ZM', 'EE', 'ZW', 'BG', 'MD', 'GR', 'SD', 'RO', 'SS', 'NO', 'TR', 'LV', 'EG', 'RU', 'BY'},
  29: {'AQ', 'TZ', 'BI', 'LS', 'GR', 'SD', 'ZM', 'SS', 'UA', 'TR', 'FI', 'ZW', 'BY', 'NO', 'RU', 'BW', 'CD', 'RW', 'ZA', 'BG', 'MD', 'UG', 'EG', 'RO'},
  30: {'AQ', 'TZ', 'BI', 'LS', 'SZ', 'SD', 'ZM', 'SS', 'UA', 'TR', 'FI', 'ZW', 'BY', 'MZ', 'NO', 'RU', 'RW', 'CD', 'BW', 'ZA', 'MD', 'UG', 'EG', 'RO'},
  31: {'AQ', 'UA', 'TZ', 'MZ', 'BI', 'CD', 'RW', 'FI', 'ZA', 'ZM', 'SZ', 'ZW', 'SD', 'RO', 'SS', 'NO', 'TR', 'UG', 'EG', 'RU', 'BY'},
  32: {'AQ', 'TZ', 'MZ', 'BY', 'CD', 'ZM', 'ZA', 'FI', 'SZ', 'ZW', 'MW', 'SD', 'CY', 'SS', 'NO', 'TR', 'UG', 'EG', 'RU', 'UA'},
  33: {'AQ', 'TZ', 'MZ', 'ZM', 'ZA', 'ET', 'ZW', 'MW', 'SZ', 'SD', 'CY', 'SS', 'NO', 'KE', 'TR', 'UG', 'EG', 'RU', 'UA'},
  34: {'AQ', 'TZ', 'MZ', 'ZM', 'IL', 'ZA', 'ET', 'MW', 'ZW', 'PS', 'SA', 'SD', 'CY', 'SS', 'NO', 'KE', 'TR', 'UG', 'EG', 'RU', 'UA', 'PS'},
  35: {'AQ', 'TZ', 'MZ', 'LB', 'JO', 'IL', 'ET', 'MW', 'SY', 'PS', 'SA', 'SD', 'CY', 'SS', 'NO', 'KE', 'TR', 'UG', 'EG', 'RU', 'UA', 'PS'},
  36: {'AQ', 'ER', 'TZ', 'MZ', 'LB', 'JO', 'IL', 'ET', 'SY', 'MW', 'PS', 'SA', 'SD', 'SS', 'KE', 'TR', 'UG', 'EG', 'RU', 'UA', 'PS'},
  37: {'AQ', 'ER', 'TZ', 'MZ', 'LB', 'JO', 'ZA', 'ET', 'SY', 'SA', 'SD', 'KE', 'TR', 'EG', 'RU', 'UA'},
  38: {'AQ', 'ER', 'TZ', 'MZ', 'JO', 'ZA', 'ET', 'SY', 'SA', 'SD', 'KE', 'TR', 'IQ', 'RU', 'UA'},
  39: {'AQ', 'ER', 'TZ', 'MZ', 'JO', 'ZA', 'ET', 'SY', 'SA', 'SD', 'KE', 'TR', 'IQ', 'RU', 'UA'},
  40: {'AQ', 'ER', 'TZ', 'MZ', 'JO', 'GE', 'ET', 'SY', 'SA', 'SO', 'KE', 'TR', 'IQ', 'RU', 'UA'},
  41: {'AQ', 'ER', 'TZ', 'MZ', 'GE', 'DJ', 'ET', 'SY', 'SA', 'SO', 'YE', 'KE', 'TR', 'IQ', 'RU'},
  42: {'AQ', 'ER', 'MZ', 'GE', 'DJ', 'ET', 'SY', 'SA', 'SO', 'YE', 'KE', 'TR', 'MG', 'IQ', 'RU'},
  43: {'AQ', 'ER', 'GE', 'DJ', 'ET', 'SY', 'SA', 'SO', 'YE', 'TR', 'MG', 'AM', 'IQ', 'RU', 'KM'},
  44: {'AQ', 'ER', 'FR', 'RU', 'IR', 'DJ', 'ET', 'SA', 'SO', 'YE', 'TR', 'MG', 'AM', 'IQ', 'GE', 'KM'},
  45: {'AQ', 'FR', 'IR', 'RU', 'ET', 'AZ', 'SA', 'SO', 'YE', 'TR', 'MG', 'AM', 'IQ', 'GE', 'KM'},
  46: {'AQ', 'KZ', 'FR', 'IR', 'GE', 'ET', 'AM', 'SA', 'SO', 'YE', 'MG', 'AZ', 'IQ', 'RU'},
  47: {'AQ', 'KZ', 'QA', 'IR', 'KW', 'GE', 'ET', 'SA', 'SO', 'YE', 'MG', 'AZ', 'IQ', 'RU', 'TF'},
  48: {'AQ', 'QA', 'KZ', 'IR', 'KW', 'SA', 'SO', 'YE', 'MG', 'AZ', 'IQ', 'RU', 'TF'},
  49: {'AQ', 'KZ', 'QA', 'FR', 'IR', 'KW', 'SA', 'SO', 'YE', 'MG', 'AZ', 'RU', 'TF'},
  50: {'AQ', 'QA', 'KZ', 'FR', 'SC', 'IR', 'SA', 'SO', 'YE', 'MG', 'AZ', 'RU', 'TF'},
  51: {'AQ', 'QA', 'KZ', 'FR', 'SC', 'OM', 'IR', 'SA', 'SO', 'AE', 'YE', 'MG', 'RU', 'TF'},
  52: {'AQ', 'KZ', 'QA', 'SC', 'OM', 'IR', 'SA', 'SO', 'AE', 'TM', 'YE', 'RU', 'TF'},
  53: {'AQ', 'KZ', 'SC', 'OM', 'IR', 'SA', 'AE', 'TM', 'YE', 'RU', 'TF'},
  54: {'AQ', 'KZ', 'QA', 'SC', 'OM', 'IR', 'SA', 'AE', 'TM', 'YE', 'RU', 'TF'},
  55: {'AQ', 'QA', 'KZ', 'OM', 'UZ', 'IR', 'SA', 'AE', 'TM', 'RU', 'TF', 'RE'},
  56: {'AQ', 'KZ', 'QA', 'UZ', 'OM', 'IR', 'SA', 'AE', 'TM', 'RU', 'TF', 'RE'},
  57: {'AQ', 'KZ', 'OM', 'UZ', 'IR', 'AE', 'TM', 'RU', 'MU', 'TF'},
  58: {'AQ', 'KZ', 'OM', 'UZ', 'IR', 'TM', 'RU', 'MU', 'TF'},
  59: {'AQ', 'KZ', 'OM', 'UZ', 'IR', 'TM', 'RU', 'TF'},
  60: {'AQ', 'KZ', 'UZ', 'OM', 'IR', 'RU', 'TM', 'AF', 'TF'},
  61: {'AQ', 'KZ', 'PK', 'AF', 'UZ', 'IR', 'TM', 'RU', 'TF'},
  62: {'AQ', 'KZ', 'PK', 'AF', 'UZ', 'IR', 'TM', 'RU', 'TF'},
  63: {'AQ', 'KZ', 'PK', 'AF', 'UZ', 'IR', 'TM', 'RU', 'TF'},
  64: {'AQ', 'KZ', 'PK', 'AF', 'UZ', 'IR', 'TM', 'RU', 'TF'},
  65: {'AQ', 'KZ', 'PK', 'AF', 'UZ', 'TM', 'RU', 'TF'},
  66: {'AQ', 'KZ', 'PK', 'AF', 'UZ', 'TM', 'RU', 'TF'},
  67: {'AQ', 'KZ', 'PK', 'FR', 'UZ', 'TJ', 'AF', 'TM', 'RU', 'TF'},
  68: {'AQ', 'KZ', 'PK', 'FR', 'UZ', 'IN', 'TJ', 'AF', 'RU', 'TF'},
  69: {'AQ', 'KZ', 'PK', 'FR', 'IN', 'UZ', 'TJ', 'AF', 'KG', 'RU', 'TF'},
  70: {'AQ', 'KZ', 'PK', 'FR', 'AF', 'UZ', 'IN', 'TJ', 'KG', 'RU', 'TF'},
  71: {'AQ', 'KZ', 'PK', 'FR', 'AF', 'IN', 'UZ', 'TJ', 'KG', 'RU', 'TF'},
  72: {'AQ', 'KZ', 'PK', 'MV', 'AF', 'IN', 'UZ', 'TJ', 'KG', 'RU', 'TF'},
  73: {'AQ', 'KZ', 'PK', 'MV', 'IN', 'UZ', 'AU', 'TJ', 'AF', 'KG', 'RU', 'TF'},
  74: {'AQ', 'KZ', 'PK', 'MV', 'IN', 'AU', 'TJ', 'AF', 'KG', 'CN', 'RU', 'TF'},
  75: {'AQ', 'KZ', 'PK', 'AF', 'IN', 'TJ', 'KG', 'CN', 'RU', 'TF'},
  76: {'AQ', 'KZ', 'PK', 'IN', 'KG', 'CN', 'RU', 'TF'},
  77: {'AQ', 'KZ', 'PK', 'IN', 'KG', 'CN', 'RU'},
  78: {'AQ', 'KZ', 'CN', 'IN', 'RU', 'KG'},
  79: {'AQ', 'KZ', 'LK', 'IN', 'KG', 'CN', 'RU'},
  80: {'AQ', 'KZ', 'LK', 'NP', 'IN', 'KG', 'CN', 'RU'},
  81: {'AQ', 'KZ', 'LK', 'NP', 'IN', 'CN', 'RU'},
  82: {'AQ', 'KZ', 'LK', 'NP', 'IN', 'CN', 'RU'},
  83: {'AQ', 'KZ', 'LK', 'NP', 'IN', 'CN', 'RU'},
  84: {'AQ', 'KZ', 'CN', 'NP', 'RU', 'IN'},
  85: {'AQ', 'KZ', 'CN', 'NP', 'RU', 'IN'},
  86: {'AQ', 'KZ', 'CN', 'NP', 'RU', 'IN'},
  87: {'AQ', 'MN', 'KZ', 'NP', 'IN', 'CN', 'RU'},
  88: {'AQ', 'MN', 'NP', 'IN', 'BD', 'BT', 'CN', 'RU'},
  89: {'AQ', 'MN', 'NP', 'IN', 'BD', 'BT', 'CN', 'RU'},
  90: {'AQ', 'MN', 'IN', 'BD', 'BT', 'CN', 'RU'},
  91: {'AQ', 'MN', 'IN', 'BD', 'BT', 'CN', 'RU'},
  92: {'AQ', 'MN', 'IN', 'BD', 'BT', 'CN', 'MM', 'RU'},
  93: {'AQ', 'MN', 'IN', 'BD', 'BT', 'CN', 'MM', 'RU'},
  94: {'AQ', 'MN', 'ID', 'IN', 'CN', 'MM', 'RU'},
  95: {'AQ', 'MN', 'ID', 'IN', 'CN', 'MM', 'RU'},
  96: {'AQ', 'MN', 'ID', 'IN', 'CN', 'MM', 'RU'},
  97: {'AQ', 'MN', 'TH', 'ID', 'IN', 'AU', 'CN', 'MM', 'RU'},
  98: {'AQ', 'MN', 'TH', 'ID', 'IN', 'CN', 'MM', 'RU'},
  99: {'AQ', 'MN', 'TH', 'MY', 'ID', 'CN', 'MM', 'RU'},
  100: {'AQ', 'MN', 'TH', 'MY', 'ID', 'LA', 'CN', 'MM', 'RU'},
  101: {'AQ', 'MN', 'TH', 'MY', 'ID', 'LA', 'CN', 'MM', 'RU'},
  102: {'AQ', 'MN', 'TH', 'MY', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU'},
  103: {'AQ', 'MN', 'TH', 'MY', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU', 'SG'},
  104: {'AQ', 'MN', 'TH', 'MY', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU', 'SG'},
  105: {'AQ', 'MN', 'TH', 'MY', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU'},
  106: {'AQ', 'MN', 'TH', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU'},
  107: {'AQ', 'MN', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU'},
  108: {'AQ', 'MN', 'ID', 'KH', 'LA', 'CN', 'VN', 'RU'},
  109: {'AQ', 'MN', 'MY', 'ID', 'CN', 'VN', 'RU'},
  110: {'AQ', 'MN', 'MY', 'ID', 'CN', 'VN', 'RU'},
  111: {'AQ', 'MN', 'CN', 'MY', 'ID', 'RU'},
  112: {'AQ', 'MN', 'CN', 'MY', 'ID', 'RU'},
  113: {'AQ', 'MN', 'MY', 'ID', 'AU', 'CN', 'RU'},
  114: {'AQ', 'MN', 'MY', 'ID', 'BN', 'AU', 'CN', 'RU'},
  115: {'AQ', 'MN', 'MY', 'BN', 'ID', 'AU', 'CN', 'RU'},
  116: {'AQ', 'MN', 'MY', 'ID', 'BN', 'AU', 'CN', 'PH', 'RU'},
  117: {'AQ', 'MN', 'MY', 'ID', 'AU', 'CN', 'PH', 'RU'},
  118: {'AQ', 'MN', 'MY', 'ID', 'AU', 'CN', 'PH', 'RU'},
  119: {'AQ', 'MN', 'MY', 'ID', 'AU', 'TW', 'CN', 'PH', 'RU'},
  120: {'AQ', 'MN', 'MY', 'ID', 'AU', 'TW', 'CN', 'PH', 'RU'},
  121: {'AQ', 'ID', 'AU', 'TW', 'CN', 'PH', 'RU'},
  122: {'AQ', 'ID', 'AU', 'TW', 'CN', 'PH', 'RU'},
  123: {'AQ', 'ID', 'JP', 'AU', 'TW', 'CN', 'PH', 'RU'},
  124: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'TL', 'PH', 'RU'},
  125: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'TL', 'PH', 'RU'},
  126: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'TL', 'PH', 'RU'},
  127: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'TL', 'PH', 'RU'},
  128: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'RU'},
  129: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'RU'},
  130: {'AQ', 'ID', 'KR', 'JP', 'KP', 'AU', 'CN', 'RU'},
  131: {'AQ', 'ID', 'JP', 'KP', 'AU', 'CN', 'RU'},
  132: {'AQ', 'CN', 'ID', 'AU', 'RU', 'JP'},
  133: {'AQ', 'CN', 'ID', 'AU', 'RU', 'JP'},
  134: {'AQ', 'CN', 'ID', 'AU', 'RU', 'JP'},
  135: {'AQ', 'ID', 'AU', 'RU', 'JP'},
  136: {'AQ', 'ID', 'AU', 'RU', 'JP'},
  137: {'AQ', 'ID', 'AU', 'RU', 'JP'},
  138: {'AQ', 'ID', 'AU', 'RU', 'JP'},
  139: {'AQ', 'FM', 'ID', 'AU', 'RU', 'JP'},
  140: {'AQ', 'ID', 'FM', 'AU', 'RU', 'JP'},
  141: {'AQ', 'ID', 'PG', 'JP', 'FM', 'AU', 'RU'},
  142: {'AQ', 'ID', 'AU', 'PG', 'RU', 'JP'},
  143: {'AQ', 'AU', 'PG', 'RU', 'JP'},
  144: {'AQ', 'AU', 'PG', 'RU', 'JP'},
  145: {'AQ', 'AU', 'PG', 'US', 'RU', 'JP'},
  146: {'AQ', 'PG', 'US', 'JP', 'FM', 'AU', 'RU'},
  147: {'AQ', 'PG', 'FM', 'AU', 'RU'},
  148: {'AQ', 'FM', 'AU', 'PG', 'RU'},
  149: {'AQ', 'FM', 'AU', 'PG', 'RU'},
  150: {'AQ', 'PG', 'FM', 'AU', 'RU'},
  151: {'AQ', 'FM', 'AU', 'PG', 'RU'},
  152: {'AQ', 'PG', 'FM', 'AU', 'RU'},
  153: {'AQ', 'PG', 'FM', 'AU', 'RU'},
  154: {'AQ', 'FM', 'PG', 'RU'},
  155: {'AQ', 'SB', 'FM', 'PG', 'RU'},
  156: {'AQ', 'SB', 'FM', 'PG', 'RU'},
  157: {'AQ', 'SB', 'FM', 'RU'},
  158: {'AQ', 'SB', 'FM', 'FR', 'RU'},
  159: {'AQ', 'FM', 'SB', 'AU', 'FR', 'RU'},
  160: {'AQ', 'SB', 'FR', 'RU', 'MH'},
  161: {'AQ', 'SB', 'RU', 'MH'},
  162: {'AQ', 'SB', 'FR', 'RU', 'MH', 'NC'},
  163: {'AQ', 'SB', 'FR', 'RU', 'MH', 'NC'},
  164: {'AQ', 'FR', 'RU', 'MH', 'NC'},
  165: {'AQ', 'SB', 'FR', 'NZ', 'RU', 'MH', 'NC'},
  166: {'AQ', 'FR', 'VU', 'SB', 'NZ', 'RU', 'MH', 'NC'},
  167: {'AQ', 'FR', 'VU', 'SB', 'NZ', 'RU', 'MH', 'NC'},
  168: {'AQ', 'FR', 'VU', 'SB', 'AU', 'NZ', 'RU', 'MH', 'NC'},
  169: {'AQ', 'VU', 'NZ', 'FR', 'RU', 'MH', 'NC'},
  170: {'AQ', 'VU', 'NZ', 'RU', 'MH', 'NC'},
  171: {'AQ', 'VU', 'NZ', 'RU', 'MH'},
  172: {'AQ', 'KI', 'NZ', 'RU', 'MH'},
  173: {'AQ', 'MH', 'KI', 'NZ', 'RU', 'US'},
  174: {'AQ', 'KI', 'NZ', 'RU'},
  175: {'AQ', 'NZ', 'RU'},
  176: {'AQ', 'NZ', 'RU', 'FJ'},
  177: {'AQ', 'NZ', 'US', 'RU', 'FJ'},
  178: {'AQ', 'NZ', 'US', 'RU', 'FJ'},
  179: {'AQ', 'NZ', 'RU', 'FJ'},
  -179: {'AQ', 'TO', 'FJ', 'RU', 'US'},
  -178: {'AQ', 'NZ', 'TO', 'FJ', 'RU', 'US'},
  -177: {'AQ', 'NZ', 'RU', 'US'},
  -176: {'AQ', 'NZ', 'TO', 'RU', 'US'},
  -175: {'AQ', 'NZ', 'TO', 'RU', 'US'},
  -174: {'AQ', 'TO', 'RU', 'US'},
  -173: {'AQ', 'TK', 'TO', 'WS', 'RU', 'US'},
  -172: {'AQ', 'TK', 'KI', 'WS', 'RU'},
  -171: {'AQ', 'KI', 'WS', 'US', 'NU', 'TK', 'RU'},
  -170: {'AQ', 'NU', 'KI', 'RU', 'US'},
  -169: {'AQ', 'NU', 'RU', 'US'},
  -168: {'AQ', 'US'},
  -167: {'AQ', 'CK', 'US'},
  -166: {'AQ', 'CK', 'US'},
  -165: {'AQ', 'CK', 'US'},
  -164: {'AQ', 'CK', 'US'},
  -163: {'AQ', 'CK', 'US'},
  -162: {'AQ', 'CK', 'US'},
  -161: {'AQ', 'CK', 'US'},
  -160: {'AQ', 'CK', 'US'},
  -159: {'AQ', 'CK', 'US'},
  -158: {'AQ', 'CK', 'US'},
  -157: {'AQ', 'CK', 'US'},
  -156: {'AQ', 'KI', 'US'},
  -155: {'AQ', 'KI', 'FR', 'US'},
  -154: {'AQ', 'KI', 'FR', 'US'},
  -153: {'AQ', 'FR', 'US'},
  -152: {'AQ', 'FR', 'US'},
  -151: {'AQ', 'KI', 'FR', 'US'},
  -150: {'AQ', 'KI', 'FR', 'US'},
  -149: {'AQ', 'KI', 'FR', 'US'},
  -148: {'AQ', 'FR', 'US'},
  -147: {'AQ', 'FR', 'US'},
  -146: {'AQ', 'FR', 'US'},
  -145: {'AQ', 'FR', 'US'},
  -144: {'AQ', 'FR', 'US'},
  -143: {'AQ', 'FR', 'US'},
  -142: {'AQ', 'FR', 'US'},
  -141: {'AQ', 'CA', 'FR', 'US'},
  -140: {'AQ', 'CA', 'FR', 'US'},
  -139: {'AQ', 'CA', 'FR'},
  -138: {'AQ', 'CA', 'FR', 'US'},
  -137: {'AQ', 'CA', 'FR', 'US'},
  -136: {'AQ', 'CA', 'FR', 'US'},
  -135: {'AQ', 'CA', 'FR', 'US'},
  -134: {'AQ', 'CA', 'FR', 'US'},
  -133: {'AQ', 'CA', 'US'},
  -132: {'AQ', 'CA', 'US'},
  -131: {'AQ', 'CA', 'US'},
  -130: {'AQ', 'CA', 'US'},
  -129: {'AQ', 'CA'},
  -128: {'AQ', 'CA'},
  -127: {'AQ', 'CA'},
  -126: {'AQ', 'CA'},
  -125: {'AQ', 'CA', 'US'},
  -124: {'AQ', 'CA', 'US'},
  -123: {'AQ', 'CA', 'US'},
  -122: {'AQ', 'CA', 'US'},
  -121: {'AQ', 'CA', 'US'},
  -120: {'AQ', 'CA', 'US'},
  -119: {'AQ', 'CA', 'US'},
  -118: {'AQ', 'MX', 'CA', 'US'},
  -117: {'AQ', 'MX', 'CA', 'US'},
  -116: {'AQ', 'MX', 'CA', 'US'},
  -115: {'AQ', 'MX', 'CA', 'US'},
  -114: {'AQ', 'MX', 'CA', 'US'},
  -113: {'AQ', 'MX', 'CA', 'US'},
  -112: {'AQ', 'MX', 'CA', 'US'},
  -111: {'AQ', 'MX', 'CA', 'US'},
  -110: {'AQ', 'MX', 'CA', 'US'},
  -109: {'AQ', 'MX', 'CA', 'US'},
  -108: {'AQ', 'MX', 'CA', 'US'},
  -107: {'AQ', 'MX', 'CA', 'US'},
  -106: {'AQ', 'MX', 'CA', 'US'},
  -105: {'AQ', 'MX', 'CA', 'US'},
  -104: {'AQ', 'MX', 'CA', 'US'},
  -103: {'AQ', 'MX', 'CA', 'US'},
  -102: {'AQ', 'MX', 'CA', 'US'},
  -101: {'AQ', 'MX', 'CA', 'US'},
  -100: {'AQ', 'MX', 'CA', 'US'},
  -99: {'AQ', 'MX', 'CA', 'US'},
  -98: {'AQ', 'MX', 'CA', 'US'},
  -97: {'AQ', 'MX', 'CA', 'US'},
  -96: {'AQ', 'MX', 'CA', 'US'},
  -95: {'AQ', 'MX', 'CA', 'US'},
  -94: {'AQ', 'MX', 'CA', 'US'},
  -93: {'AQ', 'MX', 'CA', 'GT', 'EC', 'US'},
  -92: {'AQ', 'MX', 'GT', 'CA', 'EC', 'US'},
  -91: {'AQ', 'MX', 'GT', 'CA', 'EC', 'US'},
  -90: {'AQ', 'GT', 'BZ', 'US', 'SV', 'CA', 'HN', 'EC', 'MX'},
  -89: {'AQ', 'GT', 'BZ', 'US', 'SV', 'CA', 'HN', 'EC', 'MX'},
  -88: {'AQ', 'BZ', 'US', 'SV', 'CA', 'HN', 'NI', 'MX'},
  -87: {'AQ', 'BZ', 'US', 'CA', 'HN', 'NI', 'MX'},
  -86: {'AQ', 'US', 'CR', 'CA', 'HN', 'NI', 'CU'},
  -85: {'AQ', 'US', 'CR', 'CA', 'HN', 'PE', 'NI', 'CU'},
  -84: {'AQ', 'US', 'CR', 'CA', 'HN', 'PE', 'NI', 'CU'},
  -83: {'AQ', 'US', 'CR', 'CA', 'PA', 'HN', 'PE', 'NI', 'CU'},
  -82: {'AQ', 'US', 'CR', 'CA', 'PA', 'PE', 'EC', 'CU', 'CO'},
  -81: {'AQ', 'BS', 'US', 'CA', 'PA', 'PE', 'EC', 'CU', 'CO'},
  -80: {'AQ', 'BS', 'US', 'CA', 'PA', 'PE', 'EC', 'CU', 'CO'},
  -79: {'AQ', 'BS', 'US', 'JM', 'CA', 'PA', 'PE', 'EC', 'CU', 'CO'},
  -78: {'AQ', 'BS', 'US', 'JM', 'CA', 'PA', 'PE', 'EC', 'CU', 'CO'},
  -77: {'AQ', 'BS', 'US', 'JM', 'CA', 'CL', 'PA', 'PE', 'EC', 'CU', 'CO'},
  -76: {'AQ', 'BS', 'US', 'JM', 'CA', 'CL', 'PE', 'EC', 'CU', 'CO'},
  -75: {'AQ', 'BS', 'US', 'JM', 'CA', 'CL', 'PE', 'HT', 'CU', 'EC', 'CO'},
  -74: {'AQ', 'BS', 'US', 'CA', 'CL', 'GL', 'HT', 'PE', 'CU', 'AR', 'CO'},
  -73: {'AQ', 'BS', 'VE', 'US', 'TC', 'CA', 'CL', 'GL', 'DO', 'BR', 'HT', 'PE', 'AR', 'CO'},
  -72: {'AQ', 'BS', 'VE', 'US', 'TC', 'CA', 'CL', 'DO', 'GL', 'BR', 'PE', 'HT', 'AR', 'CO'},
  -71: {'AQ', 'VE', 'US', 'TC', 'CA', 'CL', 'DO', 'GL', 'BR', 'PE', 'HT', 'AR', 'CO'},
  -70: {'AQ', 'VE', 'US', 'CA', 'CL', 'DO', 'GL', 'BR', 'BO', 'PE', 'AR', 'NL', 'CO'},
  -69: {'AQ', 'VE', 'US', 'CA', 'CL', 'DO', 'GL', 'BR', 'BO', 'PE', 'AR', 'NL', 'CO'},
  -68: {'AQ', 'VE', 'US', 'CA', 'CL', 'GL', 'DO', 'BR', 'BO', 'PE', 'AR', 'NL', 'CO'},
  -67: {'AQ', 'VE', 'US', 'CA', 'CL', 'GL', 'BR', 'BO', 'AR', 'CO', 'PR'},
  -66: {'AQ', 'VE', 'US', 'CA', 'CL', 'GL', 'BR', 'BO', 'AR', 'PR'},
  -65: {'AQ', 'VE', 'CA', 'GL', 'BR', 'BO', 'AR', 'PR', 'VG'},
  -64: {'AQ', 'VE', 'CA', 'GL', 'BR', 'BO', 'AR', 'NL', 'VG'},
  -63: {'AQ', 'AG', 'GD', 'VE', 'CA', 'GL', 'PY', 'BR', 'BO', 'AR', 'NL', 'KN'},
  -62: {'AQ', 'AG', 'GD', 'VE', 'FR', 'LC', 'FK', 'CA', 'GL', 'TT', 'PY', 'BR', 'BO', 'NL', 'AR', 'GY', 'VC', 'DM', 'KN'},
  -61: {'AQ', 'AG', 'FR', 'VE', 'GD', 'LC', 'FK', 'CA', 'GL', 'TT', 'PY', 'BR', 'BO', 'AR', 'GY', 'VC', 'BB', 'DM'},
  -60: {'AQ', 'FR', 'VE', 'LC', 'FK', 'CA', 'GL', 'TT', 'PY', 'BR', 'BO', 'AR', 'GY', 'VC', 'BB', 'DM'},
  -59: {'AQ', 'SR', 'VE', 'FK', 'CA', 'GL', 'PY', 'BR', 'BO', 'UY', 'AR', 'GY', 'BB'},
  -58: {'AQ', 'SR', 'FK', 'CA', 'GL', 'PY', 'BR', 'BO', 'UY', 'AR', 'GY'},
  -57: {'AQ', 'SR', 'FK', 'CA', 'GL', 'PY', 'BR', 'BO', 'UY', 'AR', 'GY'},
  -56: {'AQ', 'SR', 'CA', 'GL', 'PY', 'BR', 'UY', 'AR', 'GY'},
  -55: {'AQ', 'SR', 'FR', 'CA', 'GL', 'PY', 'BR', 'UY', 'AR'},
  -54: {'AQ', 'SR', 'FR', 'CA', 'GL', 'PY', 'BR', 'UY', 'AR'},
  -53: {'AQ', 'SR', 'FR', 'CA', 'GL', 'BR', 'UY', 'AR'},
  -52: {'AQ', 'BR', 'FR', 'GL'},
  -51: {'AQ', 'BR', 'FR', 'GL'},
  -50: {'AQ', 'BR', 'GL'},
  -49: {'AQ', 'BR', 'GL'},
  -48: {'AQ', 'BR', 'GL'},
  -47: {'AQ', 'BR', 'GL'},
  -46: {'AQ', 'BR', 'GL'},
  -45: {'AQ', 'BR', 'GL'},
  -44: {'AQ', 'BR', 'GL'},
  -43: {'AQ', 'BR', 'GL'},
  -42: {'AQ', 'BR', 'GL'},
  -41: {'AQ', 'BR', 'GL'},
  -40: {'AQ', 'BR', 'GL'},
  -39: {'AQ', 'BR', 'GL', 'GS'},
  -38: {'AQ', 'BR', 'GL', 'GS'},
  -37: {'AQ', 'BR', 'GL', 'GS'},
  -36: {'AQ', 'BR', 'GL', 'GS'},
  -35: {'AQ', 'BR', 'GL', 'GS'},
  -34: {'AQ', 'GL'},
  -33: {'AQ', 'GL'},
  -32: {'AQ', 'GL', 'BR'},
  -31: {'AQ', 'GL'},
  -30: {'AQ', 'GL'},
  -29: {'AQ', 'PT', 'GL'},
  -28: {'AQ', 'PT', 'GL', 'GS'},
  -27: {'AQ', 'PT', 'GL', 'GS'},
  -26: {'AQ', 'GS', 'PT', 'GL', 'CV'},
  -25: {'AQ', 'IS', 'PT', 'GL', 'CV'},
  -24: {'AQ', 'IS', 'PT', 'GL', 'CV'},
  -23: {'AQ', 'IS', 'GL', 'CV'},
  -22: {'AQ', 'IS', 'GL', 'CV'},
  -21: {'AQ', 'IS', 'GL'},
  -20: {'AQ', 'IS', 'GL'},
  -19: {'AQ', 'IS', 'GL', 'ES'},
  -18: {'AQ', 'IS', 'MR', 'GL', 'ES', 'MA', 'PT', 'SN'},
  -17: {'AQ', 'IS', 'MR', 'GL', 'ES', 'MA', 'PT', 'SN', 'GW', 'GM'},
  -16: {'AQ', 'IS', 'MR', 'GL', 'ES', 'MA', 'PT', 'SN', 'GW', 'GM'},
  -15: {'AQ', 'EH', 'IS', 'MR', 'GL', 'ES', 'MA', 'GN', 'PT', 'SN', 'GW', 'GM'},
  -14: {'AQ', 'EH', 'IS', 'MR', 'GL', 'ES', 'SL', 'GN', 'MA', 'SN', 'GW', 'GM'},
  -13: {'AQ', 'EH', 'IS', 'MR', 'GL', 'ES', 'SL', 'MA', 'GN', 'ML', 'SN', 'GW', 'GM'},
  -12: {'AQ', 'EH', 'MR', 'GL', 'SL', 'ML', 'MA', 'GN', 'SN', 'LR', 'IE'},
  -11: {'AQ', 'EH', 'MR', 'GL', 'SL', 'ML', 'GN', 'MA', 'SN', 'LR', 'IE'},
  -10: {'AQ', 'EH', 'MR', 'ES', 'SL', 'ML', 'MA', 'GN', 'PT', 'NO', 'LR', 'IE'},
  -9: {'AQ', 'DZ', 'CI', 'EH', 'MR', 'ES', 'ML', 'MA', 'PT', 'GN', 'NO', 'LR', 'IE'},
  -8: {'AQ', 'GB', 'DZ', 'CI', 'FO', 'MR', 'ES', 'GN', 'ML', 'MA', 'PT', 'NO', 'LR', 'IE'},
  -7: {'AQ', 'GB', 'DZ', 'CI', 'FO', 'MR', 'ES', 'MA', 'ML', 'PT', 'GN', 'NO', 'LR', 'IE'},
  -6: {'AQ', 'GB', 'DZ', 'CI', 'FO', 'MR', 'IM', 'ES', 'MA', 'ML', 'PT', 'BF', 'IE', 'GI'},
  -5: {'AQ', 'GB', 'DZ', 'CI', 'FR', 'MR', 'IM', 'ES', 'MA', 'ML', 'BF', 'IE', 'GI'},
  -4: {'AQ', 'GB', 'DZ', 'CI', 'FR', 'GH', 'IM', 'ES', 'MA', 'ML', 'BF', 'GI'},
  -3: {'AQ', 'GB', 'DZ', 'CI', 'GH', 'FR', 'JE', 'ES', 'MA', 'ML', 'BF', 'GG'},
  -2: {'AQ', 'GB', 'DZ', 'FR', 'GH', 'JE', 'CI', 'ES', 'MA', 'ML', 'BF''GG'},
  -1: {'AQ', 'GB', 'DZ', 'FR', 'GH', 'JE', 'ES', 'ML', 'MA', 'BF'}
}
