countries_dict = {
  'BS': ['Bahamas', 6, 6],
  'US': ['United States', 56, 67],
  'CA': ['Canada', 1, 1],
  'IE': ['Ireland', 6, 6],
  'CZ': ['Czech Republic', 5, 7],
  'SK': ['Slovakia', 3, 4],
  'MA': ['Morocco', 2, 6],
  'HU': ['Hungary', 6, 8],
  'AT': ['Austria', 5, 7],
  'DE': ['Germany', 3, 5],
  'AD': ['Andorra', 3, 6],
  'ES': ['Spain', 5, 8],
  'PT': ['Portugal', 2, 6],
  'BE': ['Belgium', 4, 4],
  'IT': ['Italy', 6, 6],
  'FR': ['France', 1, 1],
  'GB': ['United Kingdom', 1, 1],
  'NL': ['Netherlands', 2, 3],
  'VA': ['Vatican City', 2, 4],
  'MX': ['Mexico', 1, 3]
}
