countries_dict = {
  'MC': ['Monaco', 1, 1],
  'EG': ['Egypt', 1, 1],
  'MA': ['Morocco', 5, 8],
  'UZ': ['Uzbekistan', 4, 12],
  'TR': ['Turkey', 3, 8],
  'BR': ['Brazil', 4, 14],
  'IT': ['Italy', 10, 28],
  'FR': ['France', 4, 11],
  'AT': ['Austria', 1, 1],
  'CN': ['China', 3, 10],
  'RU': ['Russia', 36, 84],
  'CU': ['Cuba', 13, 26],
  'GR': ['Greece', 6, 9],
  'NL': ['Netherlands', 1, 1],
  'AR': ['Argentina', 1, 2],
  'MY': ['Malaysia', 3, 14],
  'ES': ['Spain', 11, 23],
  'TH': ['Thailand', 16, 34],
  'AE': ['United Arab Emirates', 6, 9],
  'GB': ['United Kingdom', 3, 7],
  'HR': ['Croatia', 2, 2],
  'AZ': ['Azerbaijan', 4, 6],
  'MX': ['Mexico', 2, 6],
  'HU': ['Hungary', 2, 3],
  'PT': ['Portugal', 3, 6],
  'VA': ['Vatican City', 1, 3],
  'IL': ['Israel', 4, 6],
  'NO': ['Norway', 6, 11],
  'CY': ['Cyprus', 1, 4],
  'SE': ['Sweden', 3, 4],
  'KH': ['Cambodia', 1, 1],
  'VN': ['Vietnam', 6, 20],
  'FI': ['Finland', 1, 1]
}
