countries_dict = {
  'CN': ['China', 1, 1],
  'BR': ['Brazil', 5, 5],
  'MA': ['Morocco', 1, 1],
  'NA': ['Namibia', 10, 10],
  'GB': ['United Kingdom', 117, 185],
  'IT': ['Italy', 11, 12],
  'ES': ['Spain', 3, 3],
  'HU': ['Hungary', 1, 1],
  'ZA': ['South Africa', 4, 4],
  'PT': ['Portugal', 626, 743],
  'IN': ['India', 6, 10],
  'GR': ['Greece', 3, 3],
  'ER': ['Eritrea', 3, 3],
  'VN': ['Vietnam', 4, 4],
  'FR': ['France', 1, 1],
  'CY': ['Cyprus', 3, 3],
  'TH': ['Thailand', 1, 1],
  'TY': ['Northern Cyprus', 1, 1]
}
