countries_dict = {
  'TR': ['Turkey', 21, 24],
  'IR': ['Iran', 24, 28],
  'EE': ['Estonia', 1, 1],
  'PL': ['Poland', 26, 29],
  'IN': ['India', 12, 15],
  'DE': ['Germany', 3, 3],
  'GE': ['Georgia', 14, 17],
  'HU': ['Hungary', 1, 1],
  'AT': ['Austria', 1, 1],
  'CZ': ['Czech Republic', 7, 7],
  'AM': ['Armenia', 4, 5],
  'SE': ['Sweden', 10, 10],
  'FR': ['France', 1, 2],
  'IT': ['Italy', 9, 11],
  'LV': ['Latvia', 2, 2],
  'RU': ['Russia', 8, 8],
  'MC': ['Monaco', 1, 1],
  'SM': ['San Marino', 1, 1],
  'NO': ['Norway', 2, 3],
  'NP': ['Nepal', 6, 9],
  'LT': ['Lithuania', 2, 2],
  'TM': ['Turkmenistan', 10, 12],
  'GR': ['Greece', 1, 1],
  'UZ': ['Uzbekistan', 2, 2],
  'DK': ['Denmark', 2, 2],
  'SK': ['Slovakia', 1, 1],
  'AE': ['United Arab Emirates', 3, 3],
  'CN': ['China', 2, 2]
}
