countries_dict = {
  'AU': ['Australia', 11, 13],
  'BR': ['Brazil', 1, 1],
  'CA': ['Canada', 22, 60],
  'AL': ['Albania', 1, 4],
  'BM': ['Bermuda', 2, 2],
  'GI': ['Gibraltar', 1, 1],
  'IS': ['Iceland', 3, 4],
  'PH': ['Philippines', 2, 2],
  'PT': ['Portugal', 6, 10],
  'CH': ['Switzerland', 28, 75],
  'MC': ['Monaco', 1, 1],
  'GG': ['Guernsey', 2, 2],
  'ES': ['Spain', 22, 60],
  'NO': ['Norway', 10, 13],
  'LU': ['Luxembourg', 3, 5],
  'CZ': ['Czechia', 2, 4],
  'GL': ['Greenland', 1, 2],
  'SI': ['Slovenia', 7, 16],
  'NL': ['Netherlands', 20, 63],
  'CY': ['Cyprus', 1, 1],
  'RU': ['Russia', 5, 5],
  'IM': ['Isle of Man', 1, 1],
  'UG': ['Uganda', 1, 1],
  'JE': ['Jersey', 1, 2],
  'ME': ['Montenegro', 2, 2],
  'SE': ['Sweden', 3, 3],
  'CU': ['Cuba', 2, 2],
  'HR': ['Croatia', 68, 210],
  'UA': ['Ukraine', 1, 1],
  'PA': ['Panama', 2, 2],
  'AD': ['Andorra', 1, 1],
  'MX': ['Mexico', 3, 4],
  'MV': ['Maldives', 2, 3],
  'GB': ['United Kingdom', 132, 239],
  'FR': ['France', 45, 72],
  'IT': ['Italy', 217, 493],
  'US': ['United States of America', 227, 362],
  'DK': ['Denmark', 8, 28],
  'AT': ['Austria', 21, 27],
  'BS': ['Bahamas', 2, 16],
  'NZ': ['New Zealand', 2, 2],
  'KR': ['South Korea', 2, 3],
  'MT': ['Malta', 1, 1],
  'DE': ['Germany', 815, 1601],
  'ZA': ['South Africa', 1, 1],
  'TH': ['Thailand', 2, 2],
  'HU': ['Hungary', 3, 9],
  'PL': ['Poland', 3, 4],
  'CN': ['South China Sea Islands (disputed)', 4, 8],
  'ID': ['Indonesia', 1, 1],
  'BE': ['Belgium', 11, 29],
  'GR': ['Greece', 3, 4],
  'FI': ['Finland', 2, 3],
  'JP': ['Japan', 3, 6],
  'IE': ['Ireland', 3, 17]
}
