countries_dict = {
  'IN': ['India', 6, 6],
  'MX': ['Mexico', 110, 122],
  'VI': ['U.S. Virgin Islands', 3, 3],
  'SE': ['Sweden', 4, 5],
  'HT': ['Haiti', 5, 6],
  'MT': ['Malta', 40, 42],
  'GB': ['United Kingdom', 1943, 2104],
  'SG': ['Singapore', 14, 20],
  'VC': ['St Vincent and the Grenadines', 1, 1],
  'LC': ['St Lucia', 3, 3],
  'AG': ['Antigua and Barbuda', 3, 3],
  'IT': ['Italy', 31, 31],
  'BS': ['Bahamas', 9, 10],
  'MY': ['Malaysia', 1, 1],
  'OM': ['Oman', 3, 3],
  'HR': ['Croatia', 15, 15],
  'ES': ['Spain', 40, 45],
  'US': ['United States', 64, 72],
  'EE': ['Estonia', 1, 2],
  'BL': ['Saint Barthelemy', 1, 1],
  'GG': ['Guernsey', 4, 5],
  'HN': ['Honduras', 5, 6],
  'FR': ['France', 21, 24],
  'GR': ['Greece', 27, 27],
  'PR': ['Puerto Rico', 4, 5],
  'AE': ['United Arab Emirates', 4, 4],
  'BB': ['Barbados', 4, 4],
  'NO': ['Norway', 1, 1],
  'BE': ['Belgium', 2, 2],
  'CU': ['Cuba', 5, 6],
  'PT': ['Portugal', 3, 3]
}
