countries_dict = {
  'US': ['United States', 161, 181],
  'MY': ['Malaysia', 1, 1],
  'VC': ['St Vincent and the Grenadines', 1, 1],
  'HR': ['Croatia', 15, 15],
  'MA': ['Morocco', 6, 6],
  'IN': ['India', 8, 8],
  'ES': ['Spain', 37, 42],
  'SG': ['Singapore', 14, 20],
  'BS': ['Bahamas', 9, 10],
  'NL': ['Netherlands', 9, 10],
  'CU': ['Cuba', 5, 6],
  'IT': ['Italy', 31, 31],
  'GB': ['United Kingdom', 1931, 2085],
  'PR': ['Puerto Rico', 4, 5],
  'AE': ['United Arab Emirates', 4, 4],
  'AL': ['Albania', 1, 1],
  'BE': ['Belgium', 2, 2],
  'LC': ['St Lucia', 3, 3],
  'MT': ['Malta', 40, 42],
  'GR': ['Greece', 27, 27],
  'PK': ['Pakistan', 1, 1],
  'PT': ['Portugal', 3, 3],
  'FR': ['France', 21, 24],
  'MX': ['Mexico', 15, 15],
  'SE': ['Sweden', 6, 7],
  'AG': ['Antigua and Barbuda', 4, 4],
  'OM': ['Oman', 3, 3],
  'HT': ['Haiti', 5, 6],
  'BB': ['Barbados', 4, 4],
  'NO': ['Norway', 1, 1],
  'HN': ['Honduras', 4, 5],
  'GG': ['Guernsey', 4, 5],
  'EE': ['Estonia', 1, 2]
}
