countries_dict = {
  'CA': ['Canada', 8972, 44090],
  'CN': ['China', 16, 16],
  'AU': ['Australia', 3, 3],
  'US': ['United States', 1275, 5229],
  'CU': ['Cuba', 3, 4],
  'AT': ['Austria', 1, 1],
  'CZ': ['Czech Republic', 2, 2],
  'IT': ['Italy', 5, 5],
  'CH': ['Switzerland', 6, 6],
  'LI': ['Liechtenstein', 1, 1],
  'VI': ['U.S. Virgin Islands', 1, 1],
  'BS': ['Bahamas', 2, 2],
  'CW': ['Curaçao', 1, 1],
  'BB': ['Barbados', 1, 1],
  'GD': ['Grenada', 1, 1],
  'LC': ['St Lucia', 1, 1],
  'AG': ['Antigua and Barbuda', 1, 1],
  'BE': ['Belgium', 2, 2],
  'FR': ['France', 3, 3],
  'IN': ['India', 2, 2],
  'JP': ['Japan', 10, 13],
  'GB': ['United Kingdom', 53, 119],
  'AR': ['Argentina', 1, 4],
  'BR': ['Brazil', 3, 5],
  'ZA': ['South Africa', 64, 339],
  'RU': ['Russia', 1, 2],
  'DE': ['Germany', 70, 648],
  'IS': ['Iceland', 46, 170],
  'ES': ['Spain', 1, 1],
  'PM': ['Saint Pierre and Miquelon', 32, 80],
  'NZ': ['New Zealand', 1, 1],
  'KR': ['South Korea', 1, 1],
  'UA': ['Ukraine', 2, 2]
}
