countries_dict = {
  'AU': ['Australia', 550, 596],
  'TO': ['Tonga', 62, 73],
  'CN': ['China', 3, 3],
  'US': ['United States', 12, 12],
  'ID': ['Indonesia', 58, 67],
  'IE': ['Ireland', 29, 32],
  'NZ': ['New Zealand', 38, 38],
  'DE': ['Germany', 93, 98],
  'SB': ['Solomon Islands', 34, 37],
  'BE': ['Belgium', 33, 36],
  'FI': ['Finland', 8, 8],
  'TR': ['Turkey', 64, 73],
  'GB': ['United Kingdom', 43, 44],
  'PL': ['Poland', 40, 42],
  'NL': ['Netherlands', 26, 26],
  'SG': ['Singapore', 13, 15],
  'NF': ['Norfolk Island', 7, 7],
  'GL': ['Greenland', 2, 2],
  'ES': ['Spain', 1, 1],
  'PK': ['Pakistan', 7, 7],
  'AE': ['United Arab Emirates', 1, 1],
  'OM': ['Oman', 2, 2],
  'CA': ['Canada', 1, 1],
  'SE': ['Sweden', 3, 3],
  'DK': ['Denmark', 10, 10],
  'VU': ['Vanuatu', 8, 8],
  'KE': ['Kenya', 1, 1],
  'BI': ['Burundi', 9, 9],
  'KR': ['South Korea', 4, 4],
  'ZW': ['Zimbabwe', 1, 1],
  'ZA': ['South Africa', 1, 1],
  'TL': ['East Timor', 2, 2],
  'CK': ['Cook Islands', 5, 5],
  'FJ': ['Fiji', 1, 1],
  'UG': ['Uganda', 1, 1]
}
