countries_dict = {
  'KZ': ['Kazakhstan', 3, 4],
  'PT': ['Portugal', 2, 3],
  'AU': ['Australia', 32, 47],
  'LK': ['Sri Lanka', 1, 1],
  'FR': ['France', 23, 28],
  'IT': ['Italy', 422, 648],
  'BS': ['Bahamas', 2, 9],
  'GR': ['Greece', 22, 37],
  'CH': ['Switzerland', 10, 11],
  'RO': ['Romania', 8, 8],
  'US': ['United States', 42, 47],
  'NO': ['Norway', 4, 4],
  'CN': ['China', 18, 19],
  'NZ': ['New Zealand', 1, 2],
  'ES': ['Spain', 25, 32],
  'LT': ['Lithuania', 1, 2],
  'TR': ['Turkey', 5, 8],
  'AT': ['Austria', 1, 1],
  'CA': ['Canada', 4, 4],
  'HR': ['Croatia', 3, 3],
  'RU': ['Russia', 4, 13],
  'DE': ['Germany', 8, 11],
  'NL': ['Netherlands', 1, 2],
  'BE': ['Belgium', 2, 2],
  'MX': ['Mexico', 6, 7],
  'GI': ['Gibraltar', 1, 1],
  'GB': ['United Kingdom', 14, 21],
  'KR': ['South Korea', 3, 5],
  'JP': ['Japan', 20, 23],
  'PL': ['Poland', 1, 1],
  'LV': ['Latvia', 2, 9],
  'DK': ['Denmark', 5, 6],
  'IE': ['Ireland', 21, 26],
  'EE': ['Estonia', 1, 1]
}
