countries_dict = {
  'AM': ['Armenia', 1, 1],
  'IE': ['Ireland', 1, 1],
  'RU': ['Russia', 1, 1],
  'LB': ['Lebanon', 5, 5],
  'ES': ['Spain', 10, 13],
  'JO': ['Jordan', 1, 1],
  'GR': ['Greece', 123, 187],
  'NO': ['Norway', 1, 1],
  'IT': ['Italy', 13, 15],
  'FR': ['France', 14, 17],
  'ID': ['Indonesia', 1, 1],
  'MT': ['Malta', 1, 1],
  'JP': ['Japan', 1, 1],
  'DK': ['Denmark', 1, 1],
  'HU': ['Hungary', 2, 2],
  'CM': ['Cameroon', 1, 1],
  'GG': ['Guernsey', 1, 1],
  'AD': ['Andorra', 1, 1],
  'BE': ['Belgium', 3, 4],
  'GB': ['United Kingdom', 9, 15],
  'US': ['United States', 36, 44],
  'AL': ['Albania', 2, 4],
  'RS': ['Serbia', 1, 1],
  'TR': ['Turkey', 1, 1],
  'TH': ['Thailand', 2, 3],
  'GL': ['Greenland', 1, 1],
  'SD': ['Sudan', 2, 2],
  'NL': ['Netherlands', 2, 2],
  'TN': ['Tunisia', 2, 2],
  'EG': ['Egypt', 2, 2],
  'AU': ['Australia', 2, 2],
  'HR': ['Croatia', 1, 1],
  'SE': ['Sweden', 4, 4],
  'CH': ['Switzerland', 5, 6],
  'CA': ['Canada', 2, 2],
  'NZ': ['New Zealand', 1, 1],
  'JE': ['Jersey', 1, 1],
  'CN': ['China', 1, 1],
  'GE': ['Georgia', 1, 1],
  'BR': ['Brazil', 4, 5],
  'RO': ['Romania', 1, 1],
  'BS': ['Bahamas', 1, 1],
  'DE': ['Germany', 7, 8],
  'IN': ['India', 9, 539],
  'GA': ['Gabon', 1, 1],
  'CZ': ['Czech Republic', 1, 1]
}
