countries_dict = {
  'AT': ['Austria', 6, 6],
  'TR': ['Turkey', 7, 7],
  'AD': ['Andorra', 3, 3],
  'CH': ['Switzerland', 13, 13],
  'IL': ['Israel', 37, 39],
  'IT': ['Italy', 20, 20],
  'PT': ['Portugal', 7, 7],
  'IR': ['Iran', 2, 2],
  'JO': ['Jordan', 4, 4],
  'CZ': ['Czech Republic', 3, 3],
  'KH': ['Cambodia', 5, 5],
  'MX': ['Mexico', 7, 7],
  'GE': ['Abkhazia', 14, 14],
  'CA': ['Canada', 17, 17],
  'LU': ['Luxembourg', 1, 1],
  'RO': ['Romania', 3, 3],
  'TJ': ['Tajikistan', 3, 3],
  'FI': ['Finland', 3, 3],
  'LV': ['Latvia', 1, 1],
  'PL': ['Poland', 3, 3],
  'DE': ['Germany', 8, 8],
  'VN': ['Vietnam', 7, 7],
  'PS': ['Palestinian Territory', 6, 6],
  'MN': ['Mongolia', 13, 13],
  'BS': ['Bahamas', 3, 3],
  'SK': ['Slovakia', 2, 2],
  'BY': ['Belarus', 1, 1],
  'MC': ['Monaco', 2, 2],
  'LI': ['Liechtenstein', 1, 1],
  'SC': ['Seychelles', 42, 42],
  'CN': ['China', 46, 46],
  'XK': ['Kosovo', 2, 2],
  'MK': ['Macedonia', 1, 1],
  'AZ': ['Azerbaijan', 17, 17],
  'AM': ['Armenia', 33, 33],
  'NP': ['Nepal', 62, 62],
  'VA': ['Vatican City', 5, 5],
  'KZ': ['Kazakhstan', 24, 24],
  'IN': ['India', 12, 12],
  'SG': ['Singapore', 5, 5],
  'MV': ['Maldives', 2, 2],
  'KG': ['Kyrgyzstan', 27, 27],
  'ID': ['Indonesia', 1, 1],
  'FR': ['France', 9, 9],
  'MM': ['Myanmar', 33, 33],
  'AL': ['Albania', 1, 1],
  'HR': ['Croatia', 7, 7],
  'AE': ['United Arab Emirates', 2, 2],
  'LK': ['Sri Lanka', 6, 6],
  'EG': ['Egypt', 2, 2],
  'ES': ['Spain', 21, 21],
  'HU': ['Hungary', 3, 3],
  'RU': ['Russia', 288, 289],
  'JM': ['Jamaica', 2, 2],
  'EE': ['Estonia', 4, 4],
  'US': ['United States', 63, 63],
  'MY': ['Malaysia', 2, 2],
  'TH': ['Thailand', 29, 29],
  'UA': ['Ukraine', 1, 1]
}
