countries_dict = {
  'US': ['United States', 303, 587],
  'CD': ['Democratic Republic of the Congo', 1, 1],
  'CU': ['Cuba', 105, 201],
  'DE': ['Germany', 2, 3],
  'TW': ['Taiwan', 1, 1],
  'MN': ['Mongolia', 1, 2],
  'LY': ['Libya', 1, 1],
  'QA': ['Qatar', 1, 1],
  'CA': ['Canada', 819, 1643],
  'GB': ['United Kingdom', 18, 22],
  'CN': ['China', 1, 1],
  'ET': ['Ethiopia', 1, 1],
  'FR': ['France', 10, 14],
  'ID': ['Indonesia', 2, 2],
  'AU': ['Australia', 1, 1],
  'NA': ['Namibia', 1, 1],
  'NZ': ['New Zealand', 1, 1],
  'IT': ['Italy', 37, 47]
}
