countries_dict = {
  'QA': ['Qatar', 1, 1],
  'CA': ['Canada', 820, 1644],
  'AU': ['Australia', 1, 1],
  'NZ': ['New Zealand', 1, 1],
  'DE': ['Germany', 2, 3],
  'GB': ['United Kingdom', 18, 22],
  'MN': ['Mongolia', 1, 2],
  'CD': ['Democratic Republic of the Congo', 1, 1],
  'IT': ['Italy', 37, 47],
  'US': ['United States', 315, 624],
  'NA': ['Namibia', 1, 1],
  'CU': ['Cuba', 116, 243],
  'ID': ['Indonesia', 1, 1],
  'ET': ['Ethiopia', 1, 1],
  'LY': ['Libya', 1, 1],
  'CN': ['China', 1, 1],
  'FR': ['France', 12, 16],
  'TW': ['Taiwan', 1, 1]
}
