countries_dict = {
  'NA': ['Namibia', 1, 1],
  'CA': ['Canada', 818, 1641],
  'LY': ['Libya', 1, 1],
  'NZ': ['New Zealand', 1, 1],
  'AU': ['Australia', 1, 1],
  'IT': ['Italy', 37, 47],
  'TW': ['Taiwan', 1, 1],
  'FR': ['France', 10, 14],
  'ET': ['Ethiopia', 1, 1],
  'CN': ['China', 1, 1],
  'CD': ['Democratic Republic of the Congo', 1, 1],
  'ID': ['Indonesia', 1, 1],
  'CU': ['Cuba', 104, 200],
  'QA': ['Qatar', 1, 1],
  'DE': ['Germany', 2, 3],
  'US': ['United States', 313, 613],
  'MN': ['Mongolia', 1, 2],
  'GB': ['United Kingdom', 18, 22]
}
